---
title: "About The Authors"
---

**Eugene Yan** designs, builds, and operates machine learning systems that serve customers at scale. He's currently a Senior Applied Scientist at Amazon where he builds [RecSys for millions worldwide](https://eugeneyan.com/speaking/recsys2022-keynote/) worldwide and applies [LLMs to serve customers better](https://eugeneyan.com/speaking/ai-eng-summit/). Previously, he led machine learning at Lazada (acquired by Alibaba) and a Healthtech Series A. He writes & speaks about ML, RecSys, LLMs, and engineering at [eugeneyan.com](https://eugeneyan.com/) and [ApplyingML.com](https://applyingml.com/).

**Bryan Bischof** is the Head of AI at Hex, where he leads the team of engineers building Magic – the data science and analytics copilot. Bryan has worked all over the data stack leading teams in analytics, machine learning engineering, data platform engineering, and AI engineering. He started the data team at Blue Bottle Coffee, led several projects at Stitch Fix, and built the data teams at Weights and Biases. Bryan previously co-authored the book Building Production Recommendation Systems with O’Reilly, and teaches Data Science and Analytics in the graduate school at Rutgers. His Ph.D. is in pure mathematics. 

**Charles Frye** teaches people to build AI applications. After publishing research in [psychopharmacology](https://pubmed.ncbi.nlm.nih.gov/24316346/) and [neurobiology](https://journals.physiology.org/doi/full/10.1152/jn.00172.2016), he got his Ph.D. at the University of California, Berkeley, for dissertation work on [neural network optimization](https://arxiv.org/abs/2003.10397). He has taught thousands the entire stack of AI application development, from linear algebra fundamentals to GPU arcana and building defensible businesses, through educational and consulting work at Weights and Biases, [Full Stack Deep Learning](https://fullstackdeeplearning.com), and Modal.

**Hamel Husain** is a machine learning engineer with over 25 years of [experience](https://www.linkedin.com/in/hamelhusain/). He has worked with innovative companies such as Airbnb and GitHub, which included <a href="https://openai.com/index/introducing-text-and-code-embeddings#:~:text=models%20on%20the-,CodeSearchNet,),-evaluation%20suite%20where">early LLM research used by OpenAI</a> for code understanding. He has also led and contributed to numerous popular [open-source machine-learning tools](https://hamel.dev/oss/opensource.html). Hamel is currently an [independent consultant](https://hamel.dev/hire.html) helping companies operationalize Large Language Models (LLMs) to accelerate their AI product journey.

**Jason Liu** is a distinguished machine learning [consultant](https://jxnl.co/services/) known for leading teams to successfully ship AI products. Jason's technical expertise covers personalization algorithms, search optimization, synthetic data generation, and MLOps systems. His experience includes companies like Stitchfix, where he created a recommendation framework and observability tools that handled 350 million daily requests. Additional roles have included Meta, NYU, and startups such as Limitless AI and Trunk Tools. 

**Shreya Shankar** is an ML engineer and PhD student in computer science at UC Berkeley. She was the first ML engineer at 2 startups, building AI-powered products from scratch that serve thousands of users daily. As a researcher, her work focuses on addressing data challenges in production ML systems through a human-centered approach. Her work has appeared in top data management and human-computer interaction venues like VLDB, SIGMOD, CIDR, and CSCW. 
