---
title: Services
description: "Paid consulting services we offer"
metadata-files: 
    - "_subscribe.yml"
---

## Problems We Solve

You should consider hiring us if:

- **You feel lost on what to prioritize and what experiments you should run.** 
    - _Goal: get to an MVP quickly._
- **You need your team to get quickly upskilled on AI, and vet potential hires.** 
    -  _Goal: become self-sufficient in months._
- **You are hitting a plateau in making your AI better.** 
    - _Goal: processes to consistently measure & improve your AI._
- **Your LLMs need to be cheaper or faster.** 
    - _Goal: tools that help you make the best tradeoffs between performance, cost and latency._
- **You are overwhelmed by tools & frameworks.** 
    - _Goal: curated tools and infrastructure specific to your use case._

## Services

We offer three types of services:

### 1. Strategic Consulting

We will save your engineering team time and money by steering them away from common pitfalls, selecting the best tools, and walking them through an approach to building AI products. Furthermore, we will introduce you to talent, vendors and partners to accelerate your goals.  

### 2. Comprehensive Consulting

Everything in strategic consulting, plus we build and deploy components of AI products for you.  We will work with your team to understand your needs, build a roadmap, and execute on it.

### 3. Workshops For Enterprise Teams

We offer 3-day workshops to help your team get up to speed on the fundamentals of AI such as RAG, Evals, Fine-Tuning, and more.  

## Pricing

The cost of our services depends on the scope of the project.  However, the following are typical prices for our services:

- Strategic Consulting: $183,600 for a 3-month engagement.
- 2-day Workshop: $125,800
- Comprehensive Consulting: $975,000 total, for an engagement that will last a minimum of 3 months.

All of our work has a money-back guarantee[^2]. To get started, please [fill out this quick form](https://llms.typeform.com/to/M8f89mlM).

## Why Us

We have a [track record](about.qmd) of building and deploying AI products in a variety of industries.  Our services are led by Hamel and Jason, with access to experts in the field including open-source maintainers and operators who are building with AI.

To get in touch, please fill out [this form](https://llms.typeform.com/to/M8f89mlM). If you have questions, you can also reach out to us at `consulting@applied-llms.org`

[^2]: The quality of our work is guaranteed. If you do not believe we have met mutually established objectives, we will continue to work toward those goals with you for no additional fee. If, after such an additional attempt, you still believe we have not met your objectives, we will refund your fees in total.